### ISSUE TITLE
Serverless deploy with Sequelize Typescript

### ISSUE THREAD

**Issue by sandeepbussspacetech** [balassy/aws-lambda-typescript#112]
Hello,

I build my project using the same farmwork and implement sequelize typescript for the data operation.

It's working fine with serverless offline.

but not working after deploy.

Thanks,

**Comment by balassy** [comment]
Hello @sandeepbussspacetech ,
Could you please be more specific what "not working" exactly means?

**Comment by balassy** [comment]
I close this because there is not enough information to reproduce the issue.
